name: CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'apps/api/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'apps/api/**'
jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Set Up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        run: pnpm --filter @stoki/api exec prisma generate

      - name: Run Unit Tests
        run: pnpm --filter @stoki/api test