name: CI

on:
  push:
    branches: [main, develop]
    paths:
      - "apps/api/**"
  pull_request:
    branches: [main, develop]
    paths:
      - "apps/api/**"
jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Set Up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        run: pnpm --filter @stoki/api exec prisma generate

      - name: Run Unit Tests
        run: pnpm --filter @stoki/api test

  e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: ${{ secrets.TEST_DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
          POSTGRES_DB: stoki_test
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Set Up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        run: pnpm --filter @stoki/api exec prisma generate

      - name: Run Migrations
        run: pnpm --filter @stoki/api exec prisma migrate deploy
        env:
          DATABASE_URL: postgresql://${{ secrets.TEST_DB_USER }}:${{ secrets.TEST_DB_PASSWORD }}@localhost:5433/stoki_test

      - name: Run Seed
        run: pnpm --filter @stoki/api exec ts-node prisma/seed-test.ts
        env:
          DATABASE_URL: postgresql://${{ secrets.TEST_DB_USER }}:${{ secrets.TEST_DB_PASSWORD }}@localhost:5433/stoki_test

      - name: Run E2E Tests
        run: pnpm --filter @stoki/api test:e2e
        env:
          DATABASE_URL: postgresql://${{ secrets.TEST_DB_USER }}:${{ secrets.TEST_DB_PASSWORD }}@localhost:5433/stoki_test
          JWT_SECRET: ${{ secrets.TEST_JWT_SECRET }}
          JWT_TTL: 3600
          JWT_REFRESH_SECRET: ${{ secrets.TEST_JWT_REFRESH_SECRET }}
          JWT_REFRESH_TTL: 86400
